apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
  labels:
    component: nginx
spec:
# like the image
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      component: nginx
# template for the pods
  template:
    metadata:
# connect with the service
      labels:
        component: nginx
    spec:
      containers:
      - name: nginx
        image: img-nginx
        imagePullPolicy: Never
        ports:
        - containerPort: 80
        - containerPort: 443
---
apiVersion: v1
kind: Service
metadata:
  name: svc-nginx
  labels:
    component: nginx
  annotations:
    metallb.universe.tf/allow-shared-ip: unifi-addr
spec:
# connect with the Deployment
  selector:
    component: nginx
  type: LoadBalancer
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 80
    - name: https
      protocol: TCP
      port: 443
      targetPort: 443
  loadBalancerIP: 192.168.99.232
