apiVersion: v1
kind: Service
metadata:
  name: svc-phpmyadmin
  annotations:
    metallb.universe.tf/allow-shared-ip: unifi-addr
spec:
  selector:
    app: phpmyadmin
  type: LoadBalancer
  ports:
  - port: 5000
    targetPort: 5000
  loadBalancerIP: 192.168.99.232

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: phpmyadmin
spec:
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: phpmyadmin
  template:
    metadata:
      labels:
        app: phpmyadmin
    spec:
      containers:
      - name: phpmyadmin
        image: img-phpmyadmin
        imagePullPolicy: Never
        ports:
        - containerPort: 5000