FROM alpine

MAINTAINER Henry Buisseret <hbuisser@student.s19.be>

RUN	apk add wget php7 php7-fpm php7-opcache php7-gd php7-mysqli php7-zlib php7-curl php7-mbstring php7-json php7-session nginx

EXPOSE 5000