apiVersion: v1
kind: Service
metadata:
  name: svc-wordpress
  annotations:
    metallb.universe.tf/allow-shared-ip: unifi-addr
spec:
  selector:
    app: wordpress
  type: LoadBalancer
  ports:
  - port: 5050
    targetPort: 5050
  loadBalancerIP: 192.168.99.232
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: wordpress
spec:
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: wordpress
  template:
    metadata:
      labels:
        app: wordpress
    spec:
      containers:
      - name: wordpress
        image: img-wordpress
        imagePullPolicy: Never
        ports:
        - containerPort: 5050