apiVersion: apps/v1
kind: Deployment
metadata:
  name: telegraf
spec:
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: telegraf
  template:
    metadata:
      labels:
        app: telegraf
    spec:
      containers:
      - name: telegraf
        image: img-telegraf
        imagePullPolicy: Never
        ports:
        - containerPort: 8125
        volumeMounts:
        - name: telegraf-endpoint
          mountPath: "/var/run/docker.sock"
      volumes:
      - name: telegraf-endpoint
        hostPath:
          path: /var/run/docker.sock
---
apiVersion: v1
kind: Service
metadata:
  name: svc-telegraf
spec:
  selector:
    app: telegraf
  type: ClusterIP
  ports:
  - port: 8125
    targetPort: 8125