FROM alpine

MAINTAINER Henry Buisseret <hbuisser@student.s19.be>

# Download :
RUN		cd /tmp && \
		wget https://dl.influxdata.com/telegraf/releases/telegraf-1.15.2_linux_amd64.tar.gz && \
		tar -zxf telegraf-1.15.2_linux_amd64.tar.gz && \
		mv telegraf-1.15.2 telegraf

